
schedule:
  - unit: "Questions and Data"
    materials:
      - href: 1-questions-and-data/01-understanding-the-world/notes.qmd
        date: 01/18/23
      - href: 1-questions-and-data/02-taxonomy-of-data/notes.qmd
        date: 01/20/23
      - href: 1-questions-and-data/03-a-tool-for-computing-with-data/notes.qmd
        date: 01/25/23
  - unit: "Summarizing Data"
    materials:
      - href: 2-summarizing-data/labs/01-arbuthnot/lab.qmd
        date: 01/25/23
      - href: 2-summarizing-data/04-summarizing-categorical-data/notes.qmd
        date: 01/27/23
      - href: 2-summarizing-data/05-summarizing-numerical-data/notes.qmd
        date: 02/01/23
      - href: 2-summarizing-data/06-a-grammar-of-graphics/notes.qmd
        date: 02/03/23
      - href: 2-summarizing-data/labs/02-class-survey/lab.qmd
        date: 02/03/23
      - title: "Quiz!"
        date: 02/06/23
      - href: 2-summarizing-data/07-conditioning/notes.qmd
        date: 02/08/23
      - href: 2-summarizing-data/labs/03-flights/lab.qmd
        date: 02/08/23
      - href: 2-summarizing-data/08-communicating-with-graphics/notes.qmd
        date: 02/10/23
      - href: 2-summarizing-data/09-summarizing-associations/notes.qmd
        date: 02/15/23
      - href: 2-summarizing-data/10-multiple-linear-regression/notes.qmd
        date: 02/17/23
  - unit: "Generalization"
    materials:
      - href: 3-generalization/11-chance-intro/notes.qmd
        date: 02/22/23
      - href: 3-generalization/12-cond-prob-indep/notes.qmd
        date: 02/24/23
      - href: 3-generalization/13-random-variables/notes.qmd
        date: 03/01/23
      - title: "Expectation and Variance"
        href: 3-generalization/14-ev-se/notes.qmd
        date: 03/03/23
      - href: 3-generalization/labs/04-elections/lab.qmd
        date: 03/03/23
      - href: 3-generalization/15-sampling-distributions/notes.qmd
        date: 03/08/23
      - href: 3-generalization/labs/05-peoples-park/lab.qmd
        date: 03/08/23
      - href: 3-generalization/16-confidence-intervals/notes.qmd
        date: 03/10/23
      - href: 3-generalization/17-bootstrapping/notes.qmd
        date: 03/15/23
      - href: 3-generalization/18-hypothesis-tests/notes.qmd
        date: 03/17/23
      - href: 3-generalization/19-hypothesis-tests-2/notes.qmd
        date: 03/22/23
      - href: 3-generalization/20-wrong-by-design/notes.qmd
        date: 03/24/23
  - unit: "Causation"
    materials:
      - href: 4-causation/21-defining-causality/notes.qmd
        date: 04/05/23
      - href: 4-causation/labs/06-taste-test/lab.qmd
        date: 04/05/23
      - href: 4-causation/22-experiments/notes.qmd
        date: 04/07/23
  - unit: "Prediction"
    materials:
      - href: 5-prediction/23-method-of-least-squares/notes.qmd
        date: 04/12/23
      - href: 5-prediction/24-improving-predictions/notes.qmd
        date: 04/14/23
      - href: 5-prediction/labs/07-sports/lab.qmd
        date: 04/14/23
      - href: 5-prediction/25-overfitting/notes.qmd
        date: 04/19/23
      - href: 5-prediction/26-case-study-home-prices/notes.qmd
        date: 04/20/23
      - href: 5-prediction/27-logistic-regression/notes.qmd
        date: 04/26/23
      - href: 5-prediction/labs/08-cancer/lab.qmd
        date: 04/26/23
      - href: 5-prediction/28-to-explain-or-to-predict/notes.qmd
        date: 04/28/23
        
auto-publish:
# how many seconds to add to 00:00 of each file's release `date`
  timezone: "America/Los_Angeles"
  live-as-of: "02/10/23"

instructors:
  - name: Andrew Bray
    email: "andrewbray@berkeley.edu"
    quartopub-name: andrew
  - name: Silas Gifford
    email: "marsonstars@berkeley.edu"
    quartopub-name: silas
  - name: Jeremy Sanchez
    email: "jeremysanchez@berkeley.edu"
    quartopub-name: sanchez
  - name: Shobhana Stoyanov
    email: "shobhana@berkeley.edu"
    quartopub-name: shobhana
    
semester: "Spring, 2023"

