
schedule:
  - unit: "Questions and Data"
    materials:
      - href: 1-questions-and-data/01-understanding-the-world/notes.qmd
        date: 08/24/23
      - href: 1-questions-and-data/02-taxonomy-of-data/notes.qmd
        date: 08/29/23
      - href: 1-questions-and-data/03-a-tool-for-computing-with-data/notes.qmd
        date: 08/31/23
  - unit: "Summarizing Data"
    materials:
      - href: 2-summarizing-data/labs/01-arbuthnot/lab.qmd
        date: 09/5/23
      - href: 2-summarizing-data/01-summarizing-categorical-data/notes.qmd
        date: 09/5/23
      - href: 2-summarizing-data/02-summarizing-numerical-data/notes.qmd
        date: 09/7/23
      - href: 2-summarizing-data/03-a-grammar-of-graphics/notes.qmd
        date: 09/12/23
      - href: 2-summarizing-data/labs/02-class-survey/lab.qmd
        date: 09/12/23
      - title: "Quiz!"
        date: 09/13/23
      - href: 2-summarizing-data/04-conditioning/notes.qmd
        date: 09/14/23
      - href: 2-summarizing-data/labs/03-flights/lab.qmd
        date: 09/14/23
      - href: 2-summarizing-data/05-communicating-with-graphics/notes.qmd
        date: 09/19/23
      - href: 2-summarizing-data/06-summarizing-associations/notes.qmd
        date: 09/21/23
      - href: 2-summarizing-data/07-multiple-linear-regression/notes.qmd
        date: 09/26/23
  - unit: "Probability"
    materials:
      - href: 3-probability/01-chance-intro/notes.qmd
        date: 09/28/23
      - href: 3-probability/02-cond-prob-indep/notes.qmd
        date: 10/3/23
      - href: 3-probability/03-random-variables/notes.qmd
        date: 10/5/23
      - title: "Expectation and Variance"
        href: 3-probability/04-ev-se/notes.qmd
        date: 10/10/23
      - href: 3-probability/labs/04-elections/lab.qmd
        date: 10/10/23
  - unit: "Generalization"
    materials:
      - href: 4-generalization/01-sampling-distributions/notes.qmd
        date: 10/12/23
      - href: 4-generalization/labs/05-peoples-park/lab.qmd
        date: 10/12/23
      - href: 4-generalization/02-confidence-intervals/notes.qmd
        date: 10/17/23
      - href: 4-generalization/03-bootstrapping/notes.qmd
        date: 10/19/23
      - href: 4-generalization/04-hypothesis-tests/notes.qmd
        date: 10/24/23
      - href: 4-generalization/05-hypothesis-tests-2/notes.qmd
        date: 10/26/23
      - href: 4-generalization/06-wrong-by-design/notes.qmd
        date: 10/31/23
  - unit: "Causation"
    materials:
      - href: 5-causation/01-defining-causality/notes.qmd
        date: 11/02/23
      - href: 5-causation/labs/06-taste-test/lab.qmd
        date: 11/02/23
      - href: 5-causation/02-experiments/notes.qmd
        date: 11/07/23
  - unit: "Prediction"
    materials:
      - href: 6-prediction/01-method-of-least-squares/notes.qmd
        date: 11/9/23
      - href: 6-prediction/02-improving-predictions/notes.qmd
        date: 11/14/23
      - href: 6-prediction/labs/07-sports/lab.qmd
        date: 11/14/23
      - href: 6-prediction/03-overfitting/notes.qmd
        date: 11/16/23
      - href: 6-prediction/04-case-study-home-prices/notes.qmd
        date: 11/28/23
      - href: 6-prediction/05-logistic-regression/notes.qmd
        date: 11/30/23
      - href: 6-prediction/labs/08-cancer/lab.qmd
        date: 11/30/23
#      - href: 6-prediction/06-to-explain-or-to-predict/notes.qmd
#        date: 04/28/23
        
auto-publish:
  timezone: "America/Los_Angeles"
  live-as-of: "09/1/23"
  notes-1-release: "Friday, 17:00" # for Tu/Weds notes
  notes-2-release: "Tuesday, 17:00" # for Thu/Fri notes

instructors:
  - name: Andrew Bray
    email: "andrewbray@berkeley.edu"
    quartopub-name: andrew
  - name: Iain Carmichael
    email: "iain@berkeley.edu"
    quartopub-name: 
  - name: Silas Gifford
    email: "silascs@berkeley.edu"
    quartopub-name: silas
  - name: Jeremy Sanchez
    email: "jeremysanchez@berkeley.edu"
    quartopub-name: sanchez
  - name: Shobhana Stoyanov
    email: "shobhana@berkeley.edu"
    quartopub-name: shobhana
    
semester: "Spring, 2023"

