on:
  workflow_dispatch:
  # schedule:
  #   - cron: "1 0 * * 5" # Every Friday at 5:01 pm (PDT)
  #   - cron: "1 13 * * 2" # Every Tuesday at 6:01 am (PDT)
  #   - cron: "1 13 * * 4" # Every Thursday at 6:01 am (PDT)

name: "Publish to gh-pages"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: stat20/stat20-docker:latest
      # Enables quarto to write output to git work directory
      options: --user root
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Accessing this repo's assets in the container
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          path: stat20

      - name: Initialize git
        run: |
          # exit if any command returns non-zero exit
          set -e

          # execute from the textbook
          cd stat20

          git config --local user.email "scf@stat.berkeley.edu"
          git config --local user.name "GitHub Actions"

      # run the container, attaching this repo as a working directory
      - name: Build the website
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # exit if any command returns non-zero exit
          set -e

          # execute from the textbook
          cd stat20

          # render and publish site
          quarto publish gh-pages --no-browser
